/**
 * Encrypted Guest Registry
 * Generated: 2026-05-20T11:12:03.354Z
 * 
 * DO NOT edit this file directly.
 * Edit guests-source.js and run: node build-guests.js
 */
const GUESTS_ENCRYPTED = {
    "0e46b39a94258d65": {
        "iv": "Ve/tWJ5fqUFGPBpH",
        "data": "6xPgz9yO6vTUMs8QR3rWZq/3ixkIYvvcwk/1ioR5uTan03p9NBE8nVqqNLKlgOJEYVwsbbdt",
        "tag": "wJHQcE2ZRc227mK6uImIUA=="
    },
    "fdeb8bc616292181": {
        "iv": "zUnS3aFjEfh4/x/C",
        "data": "04Q6vdMNS18amdWtV5Y+uA/Ss23pY7PQw1S7U40s5TNWK0i01mZJcu8oGk7ZJw89egyPoA==",
        "tag": "YrBVN3K+a0tJQ86j5M5q3A=="
    },
    "d6f9e4d64fd7bb61": {
        "iv": "FPPRHxSiN860dcqm",
        "data": "vOZx259PP1ZNXF35QMQ94/xWxaXLVkvWUPbUVrqO1Q4ZjCDXny5+72eiGYhgZyQhNbGBcrM=",
        "tag": "XCZGS3Ag9Cx+GeDRK13IHQ=="
    },
    "d47892ea0eafba04": {
        "iv": "xwGwRp0jjf0iGgZY",
        "data": "pkXym0LUs/+r5nGX2l73FXX33gNrBcG7sAdkEebg1EUGaDRjEtO5Rvi0Jm3GUt+fjCT/",
        "tag": "fETQHvm6Tz5x0G6jSb2bMg=="
    },
    "b0ab1225114a259a": {
        "iv": "FWiPE1tJm5Qpwt+3",
        "data": "KgftgXbmqJAXAEgEtzhcLPP3ioE2IB2iHcSOLyhySc3EjI02IxQaKFJY5WkBNxdhNha5",
        "tag": "cYpDKcym1dOlsMggYxjcVA=="
    },
    "a08d0810c2d508ef": {
        "iv": "gLAcCWQfdP9SMucb",
        "data": "QfFV6daBVG2zusq8Cgh/FzuLPu6imLxh9gMTHn8WV/IYOuXaJoYPMHoh7g==",
        "tag": "EfEHp+Hx8Jy0Io8GDSEfmw=="
    }
};

const GUEST_SALT = "wedding-invitation-2027";
